// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_meLR-_OMgtqm9fuuMhuosOtFZaJlJU',
    appId: '1:202654829086:web:b141dd755ad7d7f755bc0f',
    messagingSenderId: '202654829086',
    projectId: 'livelocationtracker-bcf3d',
    authDomain: 'livelocationtracker-bcf3d.firebaseapp.com',
    storageBucket: 'livelocationtracker-bcf3d.firebasestorage.app',
    measurementId: 'G-DXTDLE9294',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUJH7-D9XHhDJttuixwcZnapmp3qDgqM',
    appId: '1:202654829086:android:d8b93b3df682e86a55bc0f',
    messagingSenderId: '202654829086',
    projectId: 'livelocationtracker-bcf3d',
    storageBucket: 'livelocationtracker-bcf3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2o9TpxgG-EIuc9sDP7FH-7WpOcjcj38',
    appId: '1:202654829086:ios:ef6bfacf83a8876655bc0f',
    messagingSenderId: '202654829086',
    projectId: 'livelocationtracker-bcf3d',
    storageBucket: 'livelocationtracker-bcf3d.firebasestorage.app',
    iosBundleId: 'com.example.liveTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2o9TpxgG-EIuc9sDP7FH-7WpOcjcj38',
    appId: '1:202654829086:ios:ef6bfacf83a8876655bc0f',
    messagingSenderId: '202654829086',
    projectId: 'livelocationtracker-bcf3d',
    storageBucket: 'livelocationtracker-bcf3d.firebasestorage.app',
    iosBundleId: 'com.example.liveTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_meLR-_OMgtqm9fuuMhuosOtFZaJlJU',
    appId: '1:202654829086:web:b73f8b926762827755bc0f',
    messagingSenderId: '202654829086',
    projectId: 'livelocationtracker-bcf3d',
    authDomain: 'livelocationtracker-bcf3d.firebaseapp.com',
    storageBucket: 'livelocationtracker-bcf3d.firebasestorage.app',
    measurementId: 'G-ZLRPNJ6LF7',
  );
}
